name = "Unregistry"
uuid = "030cc32f-7cb4-4642-b348-7e786af6b19f"
repo = "https://github.com/akel123/Registry.git"
description = "private registry for unregistered packages"

[packages]
3ae50052-ad19-4e6d-841d-b95da8f55ab6 = { name = "CoexistenceHoles", path = "C/CoexistenceHoles" }
